name = "blinder_weiss"
version = "0.1.0"
defaultTargets = ["BlinderWeiss"]

[leanOptions]
autoImplicit = false
warningAsError = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "0df444a360eaa60ab8c11dca51a86af692955474"

[[lean_lib]]
name = "BlinderWeiss"
