"""JAX solver for the Blinder--Weiss (1976) lifecycle model."""

import jax

# This is a long-horizon constrained optimal-control problem. JAX defaults to
# float32, which is not adequate for its feasibility and KKT tolerances.
jax.config.update("jax_enable_x64", True)

from .bellman import (  # noqa: E402
    BellmanConfig,
    BellmanDiagnostics,
    BellmanSimulation,
    BellmanSolution,
    constant_control_transition,
    diagnose_bellman,
    endpoint_consumption_capacity,
    greedy_policy_at,
    greedy_policy_value_at,
    maximum_feasible_consumption,
    minimum_assets_during_step,
    policy_at,
    simulate_policy,
    solve_bellman,
    value_at,
)
from .bellman_convergence import (  # noqa: E402
    BellmanConvergenceConfig,
    BellmanConvergenceLevel,
    BellmanConvergenceResult,
    bellman_refinement_config,
    solve_bellman_converged,
)
from .bellman_smoothness import (  # noqa: E402
    RetirementEulerDiagnostics,
    retirement_euler_diagnostics,
)
from .calibration import (  # noqa: E402
    MOMENT_UNITS,
    AgeMomentTarget,
    CalibrationEvaluation,
    CalibrationTargets,
    InitialLawCalibrationEvaluation,
    MomentLoss,
    NumericalAcceptanceThresholds,
    compare_calibration_resolutions,
    evaluate_calibration,
    evaluate_initial_law,
    fit_initial_law_calibration,
    fit_scalar_calibration,
    weighted_age_moment_loss,
)
from .continuum import (  # noqa: E402
    InitialAtom,
    PopulationNodes,
    PopulationResult,
    PopulationStateMoments,
    SyntheticInitialDistribution,
    initial_quadrature,
    sample_initial_population,
    simulate_population,
    synthetic_initial_scenarios,
)
from .diagnostics import (  # noqa: E402
    PathDiagnostics,
    diagnose_path,
    regime_labels,
)
from .distribution import (  # noqa: E402
    DistributionDomainError,
    DistributionGrid,
    DistributionSimulation,
    DistributionStateMoments,
    LocalTransport,
    build_transport,
    initialize_distribution,
    simulate_distribution,
)
from .model import (  # noqa: E402
    ModelParams,
    benchmark_params,
    bequest_utility,
    dynamics,
    earnings_tradeoff,
    flow_utility,
)
from .population import (  # noqa: E402
    CohortMoments,
    CohortSimulation,
    cohort_moments,
    simulate_cohort,
)
from .solver import (  # noqa: E402
    CollocationResult,
    SolverConfig,
    solve_lifecycle,
    solve_mesh_sequence,
)

__all__ = [
    "endpoint_consumption_capacity",
    "maximum_feasible_consumption",
    "minimum_assets_during_step",
    "InitialLawCalibrationEvaluation",
    "NumericalAcceptanceThresholds",
    "compare_calibration_resolutions",
    "evaluate_initial_law",
    "fit_initial_law_calibration",
    "synthetic_initial_scenarios",

    "RetirementEulerDiagnostics",
    "retirement_euler_diagnostics",
    "DistributionDomainError",
    "DistributionGrid",
    "DistributionSimulation",
    "DistributionStateMoments",
    "LocalTransport",
    "build_transport",
    "initialize_distribution",
    "simulate_distribution",
    "MOMENT_UNITS",
    "AgeMomentTarget",
    "CalibrationEvaluation",
    "CalibrationTargets",
    "MomentLoss",
    "evaluate_calibration",
    "fit_scalar_calibration",
    "weighted_age_moment_loss",
    "InitialAtom",
    "PopulationNodes",
    "PopulationResult",
    "PopulationStateMoments",
    "SyntheticInitialDistribution",
    "initial_quadrature",
    "sample_initial_population",
    "simulate_population",
    "BellmanConfig",
    "BellmanConvergenceConfig",
    "BellmanConvergenceLevel",
    "BellmanConvergenceResult",
    "BellmanDiagnostics",
    "BellmanSimulation",
    "BellmanSolution",
    "CollocationResult",
    "CohortMoments",
    "CohortSimulation",
    "ModelParams",
    "PathDiagnostics",
    "SolverConfig",
    "benchmark_params",
    "bellman_refinement_config",
    "bequest_utility",
    "constant_control_transition",
    "cohort_moments",
    "diagnose_bellman",
    "diagnose_path",
    "dynamics",
    "earnings_tradeoff",
    "flow_utility",
    "greedy_policy_at",
    "greedy_policy_value_at",
    "policy_at",
    "regime_labels",
    "solve_lifecycle",
    "simulate_policy",
    "simulate_cohort",
    "solve_bellman",
    "solve_bellman_converged",
    "solve_mesh_sequence",
    "value_at",
]
